#include <libarmus.h>
#include "LED/LED.h"

void hymeDeLaJoie()
{
	LedMi('v');
	THREAD_MSleep(600);
	LedMi('v');;
	THREAD_MSleep(600);
	LedFa('v');
	THREAD_MSleep(600);
	LedSol('v');
	THREAD_MSleep(600);
	LedSol('v');
	THREAD_MSleep(600);
	LedFa('v');
	THREAD_MSleep(600);
	LedMi('v');
	THREAD_MSleep(600);
	LedRe('v');
	THREAD_MSleep(600);
	LedDo('v');
	THREAD_MSleep(600);
	LedDo('v');
	THREAD_MSleep(600);
	LedRe('v');
	THREAD_MSleep(600);
	LedMi('v');
	THREAD_MSleep(600);
	LedMi('v');
	THREAD_MSleep(1200);
	LedRe('v');
	THREAD_MSleep(1200);
	LedMi('v');
	THREAD_MSleep(600);
	LedMi('v');
	THREAD_MSleep(600);
	LedFa('v');
	THREAD_MSleep(600);
	LedSol('v');
	THREAD_MSleep(600);
	LedSol('v');
	THREAD_MSleep(600);
	LedFa('v');
	THREAD_MSleep(600);
	LedMi('v');
	THREAD_MSleep(600);
	LedRe('v');
	THREAD_MSleep(600);
	LedDo('v');
	THREAD_MSleep(600);
	LedDo('v');
	THREAD_MSleep(600);
	LedRe('v');
	THREAD_MSleep(600);
	LedMi('v');
	THREAD_MSleep(600);
	LedRe('v');
	THREAD_MSleep(1200);
	LedDo('v');
	THREAD_MSleep(1200);

}
